networks:
  server:
    external: true
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    environment:
      - TZ=${TZ}
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./letsencrypt:/etc/letsencrypt:ro
    ports:
      - 80:80
      - 443:443
    networks:
      - server
  certbot:
    container_name: certbot
    image: certbot/dns-cloudflare
    command: sh -c "certbot renew"
    entrypoint: ""
    environment:
      - TZ=${TZ}
    env_file:
      - .secrets.env
    volumes:
      - ./letsencrypt:/etc/letsencrypt
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=${UID}
      - PGID=${GID}
    volumes:
      - ./cloudflare-ddns/config.json:/config.json
    restart: always
