server {
	listen 443 quic reuseport default_server;
	listen 443 ssl default_server;

	server_name bweston.uk, www.bweston.uk;

	location / {
		return 418;
	}

	error_page 418 /418.html;
	location = /418.html {
		root /etc/nginx/html;
		internal;
	}
}

server {
	listen 443 quic;
	listen 443 ssl;

	server_name staging.bweston.uk;

	index  index.php;
	root /etc/nginx/html/website;

	location / {
		try_files $uri $uri/ =404;
	}

	location ~ \.php$ { 
		fastcgi_pass unix:/var/run/php-fpm.sock;

		fastcgi_param SCRIPT_FILENAME /var/www/html/$fastcgi_script_name;
		include fastcgi_params;
	} 
}
